#!/usr/bin/env python3
# Copyright 2026 Pravin Oli  <pravin.oli.08@gmail.com, olipravin18@gmail.com>
# Licensed under the Apache License, Version 2.0.
#
# Generate the pinwheel strawberry-bed field + planted strawberries.
#   Ground: grass (28x28) under soil (26x26); hedge wall around the boundary.
#   Beds  : model://bed, pinwheel  (TOP Q1/Q2 along Y, BOTTOM Q3/Q4 along X).
#   Plants: 3 staggered rows per bed, ~0.45 m pitch (10% canopy overlap).
#           variant mix 75% ripe + 5% each {halfripe,unripe,flower,mildew,scorch}.
#           Each CATEGORY's plants step +45 deg in yaw (varied facing).
#
# Needs both model dirs on GAZEBO_MODEL_PATH:
#   models/environment  (bed, grass_ground, soil_ground, hedge)
#   models/strawberry   (strawberry_<variant>)
# Usage:  python3 generate_strawberry_farm.py  ->  strawberry_farm.world
import os, math, random

# ----------------------------- bed field -----------------------------
BEDS_PER_QUADRANT = 6
BED_LEN, BED_W, FURROW, AISLE = 10.0, 1.0, 1.0, 2.0
YAW       = 1.5708                      # 90 deg (Y-beds)
BED_PITCH = BED_W + FURROW              # 2 m between beds in a quadrant
OFF       = AISLE / 2.0                 # 1 m off each axis
CENTER    = OFF + BED_LEN / 2.0         # along-length center (6 m)

# ----------------------------- plants --------------------------------
SEED          = 42
ROW_OFFSETS   = [-0.28, 0.0, 0.28]     # 3 rows across the 1 m bed width
PLANT_PITCH   = 0.45                    # along bed length (~10% overlap of 0.5 m)
END_MARGIN    = 0.35                    # keep plants off the bed ends
PLANT_Z       = 0.40                    # bed top
YAW_STEP      = math.radians(45)        # per-category facing step
VARIANTS = [("strawberry_ripe", 0.75), ("strawberry_halfripe", 0.05),
            ("strawberry_unripe", 0.05), ("strawberry_flower", 0.05),
            ("strawberry_mildew", 0.05), ("strawberry_leafscorch", 0.05)]
rng = random.Random(SEED)
cat_n = {v[0]: 0 for v in VARIANTS}

def pick():
    r = rng.random(); c = 0.0
    for name, w in VARIANTS:
        c += w
        if r <= c:
            return name
    return VARIANTS[0][0]

def bed_inc(name, x, y, yaw):
    return (f'    <include><uri>model://bed</uri><name>{name}</name>'
            f'<pose>{x:.3f} {y:.3f} 0 0 0 {yaw:.4f}</pose></include>\n')

def plant_inc(name, model, x, y, yaw):
    return (f'    <include><uri>model://{model}</uri><name>{name}</name>'
            f'<pose>{x:.3f} {y:.3f} {PLANT_Z} 0 0 {yaw:.4f}</pose></include>\n')

def plants_on_bed(bn, bx, by, yaw, parts):
    cy, sy = math.cos(yaw), math.sin(yaw)
    half = BED_LEN / 2.0 - END_MARGIN
    npl = int((2 * half) / PLANT_PITCH) + 1
    for ri, woff in enumerate(ROW_OFFSETS):
        stag = (PLANT_PITCH / 2.0) if (ri % 2) else 0.0
        for k in range(npl):
            l = -half + stag + k * PLANT_PITCH
            if l > half:
                continue
            wx = bx + l * cy - woff * sy        # bed-local (length l, width woff) -> world
            wy = by + l * sy + woff * cy
            m = pick()
            yawp = (cat_n[m] * YAW_STEP) % (2 * math.pi)
            cat_n[m] += 1
            parts.append(plant_inc(f"{bn}_p{ri}_{k}", m, wx, wy, yawp))

# ----------------------------- build world ---------------------------
parts = ['''<?xml version="1.0"?>
<!-- Generated by generate_strawberry_farm.py - pinwheel field + plants. -->
<sdf version="1.6">
  <world name="strawberry_farm">
    <include><uri>model://sun</uri></include>
    <include><uri>model://grass_ground</uri><pose>0 0 -0.01 0 0 0</pose></include>
    <include><uri>model://soil_ground</uri></include>
    <include><uri>model://hedge</uri><name>hedge_n</name><pose>0  14 0 0 0 0</pose></include>
    <include><uri>model://hedge</uri><name>hedge_s</name><pose>0 -14 0 0 0 0</pose></include>
    <include><uri>model://hedge</uri><name>hedge_e</name><pose>14 0 0 0 0 1.5708</pose></include>
    <include><uri>model://hedge</uri><name>hedge_w</name><pose>-14 0 0 0 0 1.5708</pose></include>
    <physics type="ode">
      <max_step_size>0.001</max_step_size>
      <real_time_update_rate>1000</real_time_update_rate>
    </physics>
''']

beds = []
for i in range(BEDS_PER_QUADRANT):
    s = OFF + BED_W / 2.0 + i * BED_PITCH
    beds.append((f"bed_q1_{i}",  s,  CENTER, YAW))   # TOP, Y-beds
    beds.append((f"bed_q2_{i}", -s,  CENTER, YAW))
    beds.append((f"bed_q4_{i}",  CENTER, -s, 0.0))   # BOTTOM, X-beds
    beds.append((f"bed_q3_{i}", -CENTER, -s, 0.0))

for bn, bx, by, yaw in beds:
    parts.append(bed_inc(bn, bx, by, yaw))
nplant0 = len(parts)
for bn, bx, by, yaw in beds:
    plants_on_bed(bn, bx, by, yaw, parts)
nplants = sum(p.count("<include") for p in parts[nplant0:])

parts.append('''
    <gui><camera name="user_camera"><pose>0 -20 22 0 0.9 1.5708</pose></camera></gui>
  </world>
</sdf>
''')

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "strawberry_farm.world")
open(out, "w").write("".join(parts))
print(f"Wrote {out}")
print(f"  {len(beds)} beds + {nplants} plants")
print(f"  variant tally: " + ", ".join(f"{k.split('_')[1]}={v}" for k, v in cat_n.items()))
print(f"  NOTE: GAZEBO_MODEL_PATH must include models/environment AND models/strawberry")
