#!/usr/bin/env python3
# Copyright 2026 Pravin Oli  <pravin.oli.08@gmail.com, olipravin18@gmail.com>
# Licensed under the Apache License, Version 2.0.
#
# Generate a 10-row strawberry farm world for Gazebo Classic, reusing the
# plastic-mulch BED and detailed STRAWBERRY-PLANT models from
#   goldmines/harvester-sim-master/harvester_gazebo/models
# (jsather, BSD). Each plant already carries ~4 ripe-red + 3 unripe + 3 green
# berries, so the field reads as ~50% ripe with flowering/unripe mixed in.
#
# Layout: N_ROWS bed-columns running along +Y, separated by drivable FURROWs,
# with clear HEADLAND space at both Y ends so the robot can exit a furrow,
# rotate, and enter the next one.  Robot drives the furrows; UV-C boom treats
# the adjacent beds.
#
# Usage:  python3 generate_strawberry_farm.py   ->  strawberry_farm.world

import os, random

# ----------------------------- tunables -----------------------------
N_ROWS         = 10      # number of bed columns (rows of the farm)
BEDS_PER_ROW   = 2       # bed tiles end-to-end along Y per row
BED_W, BED_L, BED_H = 2.0, 3.2, 0.35   # bed model native size (m)
FURROW         = 1.2     # drivable gap between bed columns (m)
HEADLAND       = 3.0     # clear turning space at each Y end (m)
PLANT_SPACING  = 0.6     # plant pitch along the bed (m)  [raise to lighten load]
BED_Z          = 0.175   # bed link height so it rests on the ground (nudge if needed)
SEED           = 7
random.seed(SEED)

ROW_PITCH = BED_W + FURROW
ROW_LEN   = BEDS_PER_ROW * BED_L
field_w   = (N_ROWS - 1) * ROW_PITCH

def inc(model, name, x, y, z, yaw=0.0):
    return (f'    <include>\n'
            f'      <uri>model://{model}</uri>\n'
            f'      <name>{name}</name>\n'
            f'      <pose>{x:.3f} {y:.3f} {z:.3f} 0 0 {yaw:.3f}</pose>\n'
            f'    </include>\n')

parts = []
parts.append('''<?xml version="1.0"?>
<!-- Generated by generate_strawberry_farm.py — 10-row strawberry farm. -->
<sdf version="1.6">
  <world name="strawberry_farm">
    <scene>
      <ambient>0.5 0.5 0.5 1</ambient>
      <background>0.7 0.85 0.95 1</background>
      <shadows>true</shadows>
    </scene>
    <include><uri>model://sun</uri></include>
    <include><uri>model://dirt_plane</uri><pose>0 0 0 0 0 0</pose></include>

    <physics type="ode">
      <max_step_size>0.001</max_step_size>
      <real_time_update_rate>1000</real_time_update_rate>
    </physics>
''')

n_plants = 0
for i in range(N_ROWS):
    x = i * ROW_PITCH
    for j in range(BEDS_PER_ROW):
        y = HEADLAND + j * BED_L + BED_L / 2.0
        parts.append(inc("bed", f"bed_{i}_{j}", x, y, BED_Z))
    # plants along this row's center line, on top of the bed
    n = int(ROW_LEN / PLANT_SPACING)
    for k in range(n):
        py = HEADLAND + PLANT_SPACING / 2.0 + k * PLANT_SPACING
        px = x + random.uniform(-0.15, 0.15)
        yaw = random.uniform(0, 6.283)
        parts.append(inc("random_strawberry_plant", f"plant_{i}_{k}", px, py, BED_H, yaw))
        n_plants += 1

# a hint camera looking down a furrow
parts.append(f'''
    <gui>
      <camera name="user_camera">
        <pose>{-3.0:.1f} {HEADLAND-2:.1f} 3.0 0 0.35 0.6</pose>
      </camera>
    </gui>
  </world>
</sdf>
''')

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "strawberry_farm.world")
open(out, "w").write("".join(parts))
print(f"Wrote {out}")
print(f"  rows={N_ROWS}  beds={N_ROWS*BEDS_PER_ROW}  plants={n_plants}")
print(f"  field: {field_w:.1f} m wide (X) x {ROW_LEN:.1f} m rows (Y) + {HEADLAND} m headland each end")
print(f"  furrow width (drive lane) = {FURROW} m ; row pitch = {ROW_PITCH} m")
